[package]
name = "BSoD"
version = "0.1.0"
edition = "2021"

[dependencies]
winapi = { version = "0.3.9", features = ["processthreadsapi", "windef", "shellapi", "winuser", "ntdef", "winbase", "errhandlingapi", "winnt", "securitybaseapi", "handleapi"] }
